kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  type: {{ .Values.service.type}}
  selector:
    tier: api
    project: deploy
  ports:
   - name: {{ .Values.service.name}}
     protocol: TCP
     port: 80
     targetPort: 80