kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: {{ .Values.service.type}}
  selector:
      app: frontend
      tier: web
      project: expense
  ports:
  - name: frontend
    protocol: TCP
    port: 80 # service port
    targetPort: {{ .Values.service.targetPort}} # container port